/**
 * Static tool definitions for browser mode.
 * Auto-generated from src/tools/ modules — 352 tools across 31 ServiceNow modules.
 * In Electron mode, tools are loaded dynamically from the running MCP server.
 */
export const TOOL_DEFINITIONS: Array<{ name: string; description: string }> = [
  { name: 'create_story', description: 'Create a new agile story/user story (requires WRITE_ENABLED=true)' },
  { name: 'update_story', description: 'Update an agile story (requires WRITE_ENABLED=true)' },
  { name: 'list_stories', description: 'List agile stories with optional sprint or state filter' },
  { name: 'create_epic', description: 'Create a new epic (requires WRITE_ENABLED=true)' },
  { name: 'update_epic', description: 'Update an epic (requires WRITE_ENABLED=true)' },
  { name: 'list_epics', description: 'List epics with optional project or state filter' },
  { name: 'create_scrum_task', description: 'Create a scrum task (sub-task of a story) (requires WRITE_ENABLED=true)' },
  { name: 'update_scrum_task', description: 'Update a scrum task (requires WRITE_ENABLED=true)' },
  { name: 'list_scrum_tasks', description: 'List scrum tasks, optionally filtered by story' },
  { name: 'list_scoped_apps', description: 'List scoped applications (custom apps) installed in the instance' },
  { name: 'get_scoped_app', description: 'Get full details of a scoped application by sys_id or scope name' },
  { name: 'create_scoped_app', description: 'Create a new scoped application in App Studio (requires WRITE_ENABLED=true). ' },
  { name: 'update_scoped_app', description: 'Update an existing scoped application (requires WRITE_ENABLED=true)' },
  { name: 'list_atf_suites', description: 'List ATF test suites in the instance' },
  { name: 'get_atf_suite', description: 'Get details of a test suite including test count' },
  { name: 'run_atf_suite', description: 'Execute an ATF test suite (requires ATF_ENABLED=true)' },
  { name: 'list_atf_tests', description: 'List ATF test cases, optionally filtered by suite' },
  { name: 'get_atf_test', description: 'Get details of a specific test case' },
  { name: 'run_atf_test', description: 'Execute a single ATF test (requires ATF_ENABLED=true)' },
  { name: 'get_atf_suite_result', description: 'Get the results of a test suite run' },
  { name: 'list_atf_test_results', description: 'List individual test results within a suite run' },
  { name: 'get_atf_failure_insight', description: 'Get ATF Failure Insight data — metadata changes between last successful and failed run (role changes, field value changes)' },
  { name: 'list_catalog_items', description: 'List available service catalog items' },
  { name: 'search_catalog', description: 'Search the service catalog for items matching a keyword' },
  { name: 'get_catalog_item', description: 'Get full details of a catalog item including its variables' },
  { name: 'create_catalog_item', description: 'Create a new service catalog item (requires WRITE_ENABLED=true)' },
  { name: 'update_catalog_item', description: 'Update an existing catalog item (requires WRITE_ENABLED=true)' },
  { name: 'order_catalog_item', description: 'Order a service catalog item (requires WRITE_ENABLED=true)' },
  { name: 'create_approval_rule', description: 'Create an approval rule that automatically generates approval requests when a record matches given conditions (requires WRITE_ENABLED=true). ' },
  { name: 'get_my_approvals', description: 'List approvals pending for the currently configured user' },
  { name: 'list_approvals', description: 'List approval requests with optional filters' },
  { name: 'approve_request', description: 'Approve a pending approval request (requires WRITE_ENABLED=true)' },
  { name: 'reject_request', description: 'Reject a pending approval request (requires WRITE_ENABLED=true)' },
  { name: 'get_sla_details', description: 'Get SLA breach status for a specific task or incident' },
  { name: 'list_active_slas', description: 'List active SLA records with optional filters' },
  { name: 'create_change_request', description: 'Create a new change request (requires WRITE_ENABLED=true)' },
  { name: 'get_change_request', description: 'Get full details of a change request by number (CHG...) or sys_id' },
  { name: 'update_change_request', description: 'Update fields on a change request (requires WRITE_ENABLED=true)' },
  { name: 'list_change_requests', description: 'List change requests with optional filtering by state or query' },
  { name: 'submit_change_for_approval', description: 'Move a change request to "Requested" state for approval (requires WRITE_ENABLED=true)' },
  { name: 'close_change_request', description: 'Close a change request with close code and notes (requires WRITE_ENABLED=true)' },
  { name: 'query_records', description: 'Query ServiceNow records with filtering, field selection, pagination, and sorting' },
  { name: 'get_table_schema', description: 'Get the structure and field information for a ServiceNow table' },
  { name: 'get_record', description: 'Retrieve complete details of a specific record by sys_id' },
  { name: 'get_user', description: 'Look up user details by email or username' },
  { name: 'get_group', description: 'Find assignment group details by name or sys_id' },
  { name: 'search_cmdb_ci', description: 'Search for configuration items (CIs) in the CMDB' },
  { name: 'get_cmdb_ci', description: 'Get complete information about a specific configuration item' },
  { name: 'list_relationships', description: 'Show parent and child relationships for a CI' },
  { name: 'list_discovery_schedules', description: 'List discovery schedules and their run status' },
  { name: 'list_mid_servers', description: 'List MID servers and verify they are healthy' },
  { name: 'list_active_events', description: 'Monitor critical infrastructure events' },
  { name: 'cmdb_health_dashboard', description: 'Get CMDB data quality metrics (completeness of server and network CI data)' },
  { name: 'service_mapping_summary', description: 'View service dependencies and related CIs for impact analysis' },
  { name: 'natural_language_search', description: 'Search ServiceNow using plain English (experimental)' },
  { name: 'natural_language_update', description: 'Update a record using natural language (experimental, requires WRITE_ENABLED=true)' },
  { name: 'list_instances', description: 'List all configured ServiceNow instances (multi-instance / multi-customer support)' },
  { name: 'switch_instance', description: 'Switch the active ServiceNow instance for this session' },
  { name: 'get_current_instance', description: 'Get the currently active ServiceNow instance name and URL' },
  { name: 'create_csm_case', description: 'Create a new Customer Service case (requires WRITE_ENABLED=true)' },
  { name: 'get_csm_case', description: 'Get full details of a CSM case by number (e.g. CS0001234) or sys_id' },
  { name: 'update_csm_case', description: 'Update fields on an existing CSM case (requires WRITE_ENABLED=true)' },
  { name: 'list_csm_cases', description: 'List CSM cases with optional filters (account, contact, state, priority)' },
  { name: 'close_csm_case', description: 'Close a CSM case with resolution details (requires WRITE_ENABLED=true)' },
  { name: 'get_csm_account', description: 'Get details of a customer account including contacts and open cases count' },
  { name: 'list_csm_accounts', description: 'List customer accounts with optional search filter' },
  { name: 'get_csm_contact', description: 'Get details of a customer contact (name, account, phone, email)' },
  { name: 'list_csm_contacts', description: 'List contacts for an account or search across all contacts' },
  { name: 'get_csm_case_sla', description: 'Get SLA details and remaining time for a CSM case' },
  { name: 'list_csm_products', description: 'List products and services available in the CSM catalog' },
  { name: 'find_artifact', description: 'Search for platform artifacts by name, type, or scope (business rules, scripts, widgets, etc.)' },
  { name: 'validate_artifact', description: 'Validate an artifact for best practices, security issues, and performance concerns' },
  { name: 'clone_artifact', description: 'Clone a platform artifact to a new name/scope. **[Scripting]**' },
  { name: 'validate_deployment', description: 'Pre-validate an update set or app before deployment — check for conflicts and missing dependencies' },
  { name: 'rollback_deployment', description: 'Rollback a deployment by reverting an update set. **[Write]**' },
  { name: 'list_deployment_history', description: 'List deployment history — committed update sets and app installs over time' },
  { name: 'create_solution_package', description: 'Create a solution package from selected update sets for distribution. **[Write]**' },
  { name: 'execute_background_script', description: 'Execute a background script on the instance (server-side JavaScript). **[Scripting]**' },
  { name: 'import_cmdb_data', description: 'Import CI data into CMDB via import set. **[Write]**' },
  { name: 'analyze_data_quality', description: 'Analyse data quality for a table — completeness, duplicates, stale records' },
  { name: 'list_devops_pipelines', description: 'List DevOps pipeline configurations registered in ServiceNow' },
  { name: 'get_devops_pipeline', description: 'Get details of a specific DevOps pipeline' },
  { name: 'list_deployments', description: 'List recent application deployments tracked in ServiceNow' },
  { name: 'get_deployment', description: 'Get details and status of a specific deployment' },
  { name: 'create_devops_change', description: 'Create a change request linked to a DevOps deployment for change governance. **[Write]**' },
  { name: 'track_deployment', description: 'Record a deployment event in ServiceNow for audit and velocity tracking. **[Write]**' },
  { name: 'get_devops_insights', description: 'Get deployment frequency, failure rate, and lead time metrics for a pipeline' },
  { name: 'list_flows', description: 'List Flow Designer flows with optional filter by name, category, or active status' },
  { name: 'get_flow', description: 'Get full details of a Flow Designer flow including its actions and trigger' },
  { name: 'trigger_flow', description: 'Trigger a Flow Designer flow with optional input parameters (requires WRITE_ENABLED=true)' },
  { name: 'get_flow_execution', description: 'Get the status and details of a specific flow execution' },
  { name: 'list_flow_executions', description: 'List recent executions of a flow with status (completed, error, running)' },
  { name: 'list_subflows', description: 'List available subflows that can be reused across flows' },
  { name: 'get_subflow', description: 'Get full details of a subflow including its inputs, outputs, and actions' },
  { name: 'list_action_instances', description: 'List reusable Flow Designer action instances available in the environment' },
  { name: 'get_process_automation', description: 'Get details of a Process Automation Designer playbook or process' },
  { name: 'list_process_automations', description: 'List Process Automation Designer playbooks and processes' },
  { name: 'create_flow', description: 'Create a new Flow Designer flow. **[Write]**' },
  { name: 'create_subflow', description: 'Create a new reusable subflow. **[Write]**' },
  { name: 'create_flow_action', description: 'Create a custom Flow Designer action. **[Scripting]**' },
  { name: 'publish_flow', description: 'Publish (activate) a draft flow or subflow. **[Write]**' },
  { name: 'test_flow', description: 'Execute a flow in test mode with sample inputs. **[Write]**' },
  { name: 'get_flow_error_log', description: 'Get detailed error logs for failed flow executions' },
  { name: 'create_hr_case', description: 'Create a new HR Service Delivery case (requires WRITE_ENABLED=true)' },
  { name: 'get_hr_case', description: 'Get full details of an HR case by number (e.g. HRCS0001234) or sys_id' },
  { name: 'update_hr_case', description: 'Update fields on an existing HR case (requires WRITE_ENABLED=true)' },
  { name: 'list_hr_cases', description: 'List HR cases with optional filters (status, subject person, service)' },
  { name: 'close_hr_case', description: 'Close an HR case with resolution notes (requires WRITE_ENABLED=true)' },
  { name: 'list_hr_services', description: 'List available HR services (Onboarding, Offboarding, Benefits, Payroll, etc.)' },
  { name: 'get_hr_service', description: 'Get details of a specific HR service including its tasks and SLAs' },
  { name: 'get_hr_profile', description: 'Get the HR profile for a user (employment details, department, manager)' },
  { name: 'update_hr_profile', description: 'Update HR profile fields for a user (requires WRITE_ENABLED=true)' },
  { name: 'list_hr_tasks', description: 'List HR tasks associated with an HR case' },
  { name: 'create_hr_task', description: 'Create a task within an HR case (requires WRITE_ENABLED=true)' },
  { name: 'get_hr_case_activity', description: 'Get the full activity log and journal entries for an HR case' },
  { name: 'create_onboarding_case', description: 'Create an employee onboarding case with all standard tasks. **[Write]**' },
  { name: 'create_offboarding_case', description: 'Create an employee offboarding case with exit tasks. **[Write]**' },
  { name: 'get_hr_lifecycle_events', description: 'Get HR lifecycle events for an employee (promotions, transfers, leaves)' },
  { name: 'list_hr_document_templates', description: 'List available HR document templates (offer letters, contracts, policies)' },
  { name: 'create_incident', description: 'Create a new incident record (requires WRITE_ENABLED=true)' },
  { name: 'get_incident', description: 'Get full details of an incident by number (e.g. INC0012345) or sys_id' },
  { name: 'update_incident', description: 'Update fields on an existing incident (requires WRITE_ENABLED=true)' },
  { name: 'resolve_incident', description: 'Resolve an incident with resolution code and notes (requires WRITE_ENABLED=true)' },
  { name: 'close_incident', description: 'Close a resolved incident (requires WRITE_ENABLED=true)' },
  { name: 'add_work_note', description: 'Add an internal work note to any ITSM record (requires WRITE_ENABLED=true)' },
  { name: 'add_comment', description: 'Add a customer-visible comment to any ITSM record (requires WRITE_ENABLED=true)' },
  { name: 'list_rest_messages', description: 'List outbound REST Message configurations (integrations with external APIs)' },
  { name: 'get_rest_message', description: 'Get full configuration of an outbound REST Message including its endpoints' },
  { name: 'list_rest_message_functions', description: 'List HTTP methods (functions) defined within a REST Message' },
  { name: 'create_rest_message', description: 'Create a new outbound REST Message definition (requires WRITE_ENABLED=true)' },
  { name: 'list_transform_maps', description: 'List Transform Maps used for importing data into ServiceNow tables' },
  { name: 'get_transform_map', description: 'Get details of a Transform Map including its field mappings' },
  { name: 'run_transform_map', description: 'Execute a Transform Map on an Import Set to load data (requires WRITE_ENABLED=true)' },
  { name: 'list_transform_field_maps', description: 'List field-level mappings within a Transform Map' },
  { name: 'list_import_sets', description: 'List Import Sets with optional filter by state or staging table' },
  { name: 'get_import_set', description: 'Get details of a specific Import Set including row count and transform status' },
  { name: 'create_import_set_row', description: 'Insert a row into an Import Set staging table for later transformation (requires WRITE_ENABLED=true)' },
  { name: 'list_data_sources', description: 'List Import Set data source definitions (file/JDBC/REST loaders)' },
  { name: 'list_event_registry', description: 'List registered event definitions in the ServiceNow event registry' },
  { name: 'get_event_registry_entry', description: 'Get details of a specific registered event definition' },
  { name: 'register_event', description: 'Register a new custom event in the event registry (requires SCRIPTING_ENABLED=true)' },
  { name: 'fire_event', description: 'Fire a custom ServiceNow event for a specific record (requires WRITE_ENABLED=true)' },
  { name: 'list_event_log', description: 'List recent event log entries (fired events and their processing status)' },
  { name: 'list_oauth_applications', description: 'List OAuth application registry entries (client applications that can authenticate)' },
  { name: 'list_credential_aliases', description: 'List connection and credential aliases used by integrations' },
  { name: 'list_assets', description: 'List IT assets with optional filtering by state, class, or assigned user' },
  { name: 'get_asset', description: 'Get full details of an IT asset including financial and lifecycle data' },
  { name: 'create_asset', description: 'Create a new IT asset record. **[Write]**' },
  { name: 'update_asset', description: 'Update an IT asset record. **[Write]**' },
  { name: 'retire_asset', description: 'Retire an IT asset (mark as disposed/retired). **[Write]**' },
  { name: 'list_software_licenses', description: 'List software license records with compliance status' },
  { name: 'get_license_compliance', description: 'Get license compliance summary — purchased vs. installed vs. in use counts' },
  { name: 'list_asset_contracts', description: 'List asset maintenance and support contracts' },
  { name: 'list_knowledge_bases', description: 'List all knowledge bases available in the instance' },
  { name: 'search_knowledge', description: 'Search knowledge base articles by keyword' },
  { name: 'get_knowledge_article', description: 'Get the full content of a knowledge article by number (KB...) or sys_id' },
  { name: 'create_knowledge_article', description: 'Create a new knowledge article (requires WRITE_ENABLED=true)' },
  { name: 'update_knowledge_article', description: 'Update a knowledge article (requires WRITE_ENABLED=true)' },
  { name: 'publish_knowledge_article', description: 'Publish a draft knowledge article (requires WRITE_ENABLED=true)' },
  { name: 'ml_predict_change_risk', description: 'Predict the risk level of a change request using historical ML analysis' },
  { name: 'ml_detect_anomalies', description: 'Run anomaly detection on operational metrics (alert volume, incident trends, etc.)' },
  { name: 'ml_forecast_incidents', description: 'Forecast incident volume for the next N days based on historical trends' },
  { name: 'ml_train_incident_classifier', description: 'Trigger training of the incident classification ML solution. **[Write]**' },
  { name: 'ml_train_change_risk', description: 'Trigger training of the change risk prediction ML model. **[Write]**' },
  { name: 'ml_train_anomaly_detector', description: 'Trigger training of an anomaly detection model for a specific table/field. **[Write]**' },
  { name: 'ml_evaluate_model', description: 'Get accuracy, training status, and metrics for a trained ML solution' },
  { name: 'ml_model_training_history', description: 'Get training run history and accuracy trends for an ML solution over time' },
  { name: 'ml_virtual_agent_nlu', description: 'Analyse Virtual Agent NLU performance — conversation completion rates and fallback metrics' },
  { name: 'ml_process_optimization', description: 'Identify process bottlenecks using analysis of task durations and reassignment patterns' },
  { name: 'list_mobile_app_configs', description: 'List ServiceNow mobile app configurations' },
  { name: 'get_mobile_app_config', description: 'Get details of a specific mobile app configuration' },
  { name: 'create_mobile_app_config', description: 'Create a new mobile app configuration. **[Write]**' },
  { name: 'list_mobile_applets', description: 'List mobile applets (mini-apps within the mobile experience)' },
  { name: 'create_mobile_applet', description: 'Create a mobile applet in a mobile app. **[Write]**' },
  { name: 'list_mobile_layouts', description: 'List mobile layout configurations' },
  { name: 'create_mobile_layout', description: 'Create a mobile layout for a specific view. **[Write]**' },
  { name: 'configure_offline_sync', description: 'Configure which tables/records are available offline in mobile. **[Write]**' },
  { name: 'send_push_notification', description: 'Send a push notification to mobile app users. **[Write]**' },
  { name: 'get_mobile_analytics', description: 'Get mobile app usage analytics — sessions, active users, popular applets' },
  { name: 'list_notifications', description: 'List email notification definitions (sysevent_email_action)' },
  { name: 'get_notification', description: 'Get full details of an email notification definition including template and conditions' },
  { name: 'create_notification', description: 'Create a new email notification definition (requires WRITE_ENABLED=true)' },
  { name: 'update_notification', description: 'Update an existing email notification (requires WRITE_ENABLED=true)' },
  { name: 'list_email_logs', description: 'List outbound email log entries to track sent/failed emails' },
  { name: 'get_email_log', description: 'Get full details of an email log entry including body and headers' },
  { name: 'list_attachments', description: 'List attachments associated with a specific record' },
  { name: 'get_attachment_metadata', description: 'Get metadata (name, type, size) of a specific attachment by its sys_id' },
  { name: 'delete_attachment', description: 'Delete an attachment from a record (requires WRITE_ENABLED=true)' },
  { name: 'upload_attachment', description: 'Upload a base64-encoded attachment to a ServiceNow record (requires WRITE_ENABLED=true). ' },
  { name: 'list_email_templates', description: 'List email notification templates used by notifications' },
  { name: 'list_notification_subscriptions', description: 'List user subscriptions to notifications (who has opted in/out)' },
  { name: 'nlq_query', description: 'Ask a natural language question and get structured ServiceNow data (ServiceNow NLQ API)' },
  { name: 'ai_search', description: 'Semantic AI-powered search across KB, catalog, incidents (ServiceNow AI Search)' },
  { name: 'generate_summary', description: 'Generate an AI summary of any record using Now Assist (latest release: sn_assist/skill/summarize)' },
  { name: 'suggest_resolution', description: 'Get AI-powered resolution suggestion for an incident based on similar past incidents' },
  { name: 'categorize_incident', description: 'Use Predictive Intelligence to predict category, assignment group, and priority (latest release: LightGBM algorithm)' },
  { name: 'get_virtual_agent_topics', description: 'List Virtual Agent topics available in the instance (latest release: streaming VA API)' },
  { name: 'trigger_agentic_playbook', description: 'Invoke an Agentic Playbook — context-aware AI agents that complete tasks autonomously ' },
  { name: 'get_ms_copilot_topics', description: 'List VA topics exposed to Microsoft Copilot 365 via Custom Engine Agent integration ' },
  { name: 'generate_work_notes', description: 'Generate AI-drafted work notes for a record based on its current context' },
  { name: 'get_pi_models', description: 'List available Predictive Intelligence solutions (classification/similarity models)' },
  { name: 'list_pa_indicators', description: 'List Performance Analytics (PA) indicators (KPIs) available in the instance' },
  { name: 'get_pa_indicator', description: 'Get details of a specific Performance Analytics indicator including its formula' },
  { name: 'get_pa_scorecard', description: 'Get current scorecard data for a PA indicator — returns current value, target, trend direction' },
  { name: 'get_pa_time_series', description: 'Get historical time-series data for a PA indicator to identify trends' },
  { name: 'list_pa_breakdowns', description: 'List PA breakdowns (dimensions) available for segmenting indicator data' },
  { name: 'list_pa_dashboards', description: 'List Performance Analytics dashboards' },
  { name: 'get_pa_dashboard', description: 'Get details of a PA dashboard including its widgets/tabs' },
  { name: 'list_homepages', description: 'List homepage dashboards (CMS content pages used as homepages)' },
  { name: 'list_pa_jobs', description: 'List Performance Analytics data collection jobs and their schedules' },
  { name: 'get_pa_job', description: 'Get details of a Performance Analytics collection job' },
  { name: 'create_dashboard', description: 'Create a new Performance Analytics dashboard (requires WRITE_ENABLED=true)' },
  { name: 'update_dashboard', description: 'Update an existing PA dashboard (requires WRITE_ENABLED=true)' },
  { name: 'check_table_completeness', description: 'Analyze data quality and field completeness for a ServiceNow table — ' },
  { name: 'get_table_record_count', description: 'Get total record count for a ServiceNow table with optional filters' },
  { name: 'compare_record_counts', description: 'Compare record counts across multiple ServiceNow tables or time periods — useful for capacity planning' },
  { name: 'list_portals', description: 'List all Service Portal configurations available in the instance' },
  { name: 'create_portal', description: 'Create a new Service Portal configuration (requires WRITE_ENABLED=true)' },
  { name: 'create_portal_page', description: 'Create a new page inside a Service Portal (requires WRITE_ENABLED=true)' },
  { name: 'get_portal', description: 'Get full configuration details of a Service Portal by sys_id or URL suffix' },
  { name: 'list_portal_pages', description: 'List pages that belong to a Service Portal' },
  { name: 'get_portal_page', description: 'Get details of a specific Service Portal page including its layout' },
  { name: 'list_portal_widgets', description: 'List Service Portal widgets with optional search by name or category' },
  { name: 'get_portal_widget', description: 'Get full source code (HTML, CSS, client/server scripts) of a Service Portal widget' },
  { name: 'create_portal_widget', description: 'Create a new Service Portal widget with template, CSS, and scripts (requires WRITE_ENABLED=true)' },
  { name: 'update_portal_widget', description: 'Update an existing Service Portal widget source code (requires WRITE_ENABLED=true)' },
  { name: 'list_widget_instances', description: 'List instances of a specific widget placed on portal pages' },
  { name: 'list_ux_apps', description: 'List Next Experience (UI Builder) applications' },
  { name: 'get_ux_app', description: 'Get configuration details of a Next Experience application' },
  { name: 'list_ux_pages', description: 'List pages within a Next Experience (UI Builder) application' },
  { name: 'list_portal_themes', description: 'List Service Portal themes (color palettes, CSS variables)' },
  { name: 'get_portal_theme', description: 'Get full details of a Service Portal theme including CSS variables' },
  { name: 'create_problem', description: 'Create a new problem record (requires WRITE_ENABLED=true)' },
  { name: 'get_problem', description: 'Get full details of a problem by number (PRB...) or sys_id' },
  { name: 'update_problem', description: 'Update fields on an existing problem (requires WRITE_ENABLED=true)' },
  { name: 'resolve_problem', description: 'Resolve a problem with root cause and resolution notes (requires WRITE_ENABLED=true)' },
  { name: 'list_reports', description: 'List saved reports in the instance (latest release: /api/now/reporting)' },
  { name: 'get_report', description: 'Get the definition and metadata of a saved report' },
  { name: 'run_aggregate_query', description: 'Run a grouped aggregate (COUNT, SUM, AVG) query on any table (latest release: /api/now/stats/{table})' },
  { name: 'trend_query', description: 'Get time-bucketed trend data for a table (useful for monthly/weekly trend charts)' },
  { name: 'get_performance_analytics', description: 'Get Performance Analytics widget data (requires PA plugin; latest release: /api/now/pa/widget/{sys_id})' },
  { name: 'export_report_data', description: 'Export raw table data as structured JSON for use in external reports' },
  { name: 'get_sys_log', description: 'Retrieve system log entries for debugging or auditing' },
  { name: 'list_scheduled_jobs', description: 'List scheduled jobs and their run schedules' },
  { name: 'get_scheduled_job', description: 'Get full details of a scheduled job by sys_id or name' },
  { name: 'create_scheduled_job', description: 'Create a new scheduled script execution job (requires WRITE_ENABLED=true)' },
  { name: 'update_scheduled_job', description: 'Update a scheduled job (requires WRITE_ENABLED=true)' },
  { name: 'trigger_scheduled_job', description: 'Immediately execute a scheduled job on-demand (requires WRITE_ENABLED=true)' },
  { name: 'create_report', description: 'Create a new saved report on any table (requires WRITE_ENABLED=true)' },
  { name: 'update_report', description: 'Update an existing saved report definition (requires WRITE_ENABLED=true)' },
  { name: 'list_job_run_history', description: 'List recent run history for scheduled jobs (success/failure log)' },
  { name: 'list_business_rules', description: 'List business rules (requires SCRIPTING_ENABLED=true)' },
  { name: 'get_business_rule', description: 'Get full details and script body of a business rule (requires SCRIPTING_ENABLED=true)' },
  { name: 'create_business_rule', description: 'Create a new business rule (requires SCRIPTING_ENABLED=true). ServiceNow supports ES2021 async/await in scripts.' },
  { name: 'update_business_rule', description: 'Update a business rule (requires SCRIPTING_ENABLED=true)' },
  { name: 'list_script_includes', description: 'List script includes (requires SCRIPTING_ENABLED=true)' },
  { name: 'get_script_include', description: 'Get full script body of a script include (requires SCRIPTING_ENABLED=true)' },
  { name: 'create_script_include', description: 'Create a new script include (requires SCRIPTING_ENABLED=true)' },
  { name: 'update_script_include', description: 'Update a script include (requires SCRIPTING_ENABLED=true)' },
  { name: 'list_client_scripts', description: 'List client scripts (requires SCRIPTING_ENABLED=true)' },
  { name: 'get_client_script', description: 'Get full details and script body of a client script (requires SCRIPTING_ENABLED=true)' },
  { name: 'list_changesets', description: 'List update sets (changesets) (requires SCRIPTING_ENABLED=true)' },
  { name: 'get_changeset', description: 'Get details of an update set (requires SCRIPTING_ENABLED=true)' },
  { name: 'commit_changeset', description: 'Commit an update set (requires SCRIPTING_ENABLED=true)' },
  { name: 'publish_changeset', description: 'Publish/export an update set to XML for deployment (requires SCRIPTING_ENABLED=true)' },
  { name: 'create_client_script', description: 'Create a new client script (onLoad, onChange, onSubmit, onCellEdit) (requires SCRIPTING_ENABLED=true)' },
  { name: 'update_client_script', description: 'Update an existing client script (requires SCRIPTING_ENABLED=true)' },
  { name: 'list_ui_policies', description: 'List UI Policies for a table (field visibility, mandatory, read-only rules) (requires SCRIPTING_ENABLED=true)' },
  { name: 'get_ui_policy', description: 'Get full details and conditions of a UI Policy (requires SCRIPTING_ENABLED=true)' },
  { name: 'create_ui_policy', description: 'Create a new UI Policy to control field behavior dynamically (requires SCRIPTING_ENABLED=true)' },
  { name: 'list_ui_actions', description: 'List UI Actions (buttons, context menus, related links) for a table (requires SCRIPTING_ENABLED=true)' },
  { name: 'get_ui_action', description: 'Get full details and script of a UI Action (requires SCRIPTING_ENABLED=true)' },
  { name: 'create_ui_action', description: 'Create a new UI Action (button or link) on a form (requires SCRIPTING_ENABLED=true)' },
  { name: 'update_ui_action', description: 'Update an existing UI Action (requires SCRIPTING_ENABLED=true)' },
  { name: 'list_acls', description: 'List Access Control rules (ACLs) — who can read/write/create/delete records (requires SCRIPTING_ENABLED=true)' },
  { name: 'get_acl', description: 'Get full details of an ACL rule including its script and role requirements (requires SCRIPTING_ENABLED=true)' },
  { name: 'create_acl', description: 'Create a new ACL rule to control access to a table or field (requires SCRIPTING_ENABLED=true)' },
  { name: 'update_acl', description: 'Update an existing ACL rule (requires SCRIPTING_ENABLED=true)' },
  { name: 'create_security_incident', description: 'Create a Security Operations incident (requires WRITE_ENABLED=true)' },
  { name: 'get_security_incident', description: 'Get full details of a security incident by number or sys_id' },
  { name: 'update_security_incident', description: 'Update a security incident record (requires WRITE_ENABLED=true)' },
  { name: 'list_security_incidents', description: 'List security incidents with filters (severity, state, category)' },
  { name: 'list_vulnerabilities', description: 'List vulnerability entries from the Vulnerability Response module' },
  { name: 'get_vulnerability', description: 'Get details of a specific vulnerability entry including CVSS score and affected CIs' },
  { name: 'update_vulnerability', description: 'Update a vulnerability entry (state, risk acceptance notes, remediation date) (requires WRITE_ENABLED=true)' },
  { name: 'list_grc_risks', description: 'List GRC (Governance, Risk, Compliance) risk entries' },
  { name: 'get_grc_risk', description: 'Get details of a GRC risk including impact, likelihood, and controls' },
  { name: 'list_grc_controls', description: 'List GRC controls with optional filter by risk or policy' },
  { name: 'get_threat_intelligence', description: 'Query threat intelligence data — IOCs, threat actors, and campaigns' },
  { name: 'list_security_playbooks', description: 'List available security response playbooks' },
  { name: 'run_security_playbook', description: 'Execute a security response playbook against an incident. **[Write]**' },
  { name: 'get_security_dashboard', description: 'Get security posture dashboard — open incidents by severity, vulnerability counts, mean time to resolve' },
  { name: 'scan_vulnerabilities', description: 'Trigger a vulnerability scan for specified CIs or groups. **[Write]**' },
  { name: 'create_grc_risk', description: 'Create a new GRC risk entry. **[Write]**' },
  { name: 'list_compliance_policies', description: 'List GRC compliance policies and their current status' },
  { name: 'get_compliance_assessment', description: 'Get compliance assessment results for a policy or control' },
  { name: 'list_audit_results', description: 'List audit results and findings' },
  { name: 'get_system_property', description: 'Get a ServiceNow system property value and metadata by name' },
  { name: 'set_system_property', description: 'Create or update a ServiceNow system property value. **[Write]**' },
  { name: 'list_system_properties', description: 'List system properties with optional filtering' },
  { name: 'delete_system_property', description: 'Delete a system property by name. **[Write]**' },
  { name: 'search_system_properties', description: 'Search system properties by name, value, or description' },
  { name: 'bulk_get_properties', description: 'Retrieve multiple system property values in a single call' },
  { name: 'bulk_set_properties', description: 'Create or update multiple system properties in a single operation. **[Write]**' },
  { name: 'export_properties', description: 'Export system properties matching a query to a JSON object (useful for environment snapshots)' },
  { name: 'import_properties', description: 'Import (create or update) system properties from a JSON object. **[Write]**' },
  { name: 'validate_property', description: 'Validate a property value against its declared type constraints without saving' },
  { name: 'list_property_categories', description: 'List all unique property categories with their record counts' },
  { name: 'get_property_history', description: 'Get audit history of changes to a system property' },
  { name: 'get_task', description: 'Get details of any task record by number or sys_id' },
  { name: 'update_task', description: 'Update fields on a task record (requires WRITE_ENABLED=true)' },
  { name: 'list_my_tasks', description: 'List tasks assigned to the currently configured user' },
  { name: 'complete_task', description: 'Mark a task as complete (requires WRITE_ENABLED=true)' },
  { name: 'get_current_update_set', description: 'Get the currently active Update Set for the session' },
  { name: 'list_update_sets', description: 'List Update Sets by state (in progress, complete, ignore)' },
  { name: 'create_update_set', description: 'Create a new Update Set and optionally switch to it. **[Scripting]**' },
  { name: 'switch_update_set', description: 'Switch the active Update Set context to a specified Update Set. **[Scripting]**' },
  { name: 'complete_update_set', description: 'Mark an Update Set as complete (ready for migration). **[Scripting]**' },
  { name: 'preview_update_set', description: 'Preview all changes contained in an Update Set' },
  { name: 'export_update_set', description: 'Get the XML export payload for an Update Set (as used in migration). **[Scripting]**' },
  { name: 'ensure_active_update_set', description: 'Ensure an active Update Set exists; create one automatically if none is in progress. **[Scripting]**' },
  { name: 'list_users', description: 'List users with optional search filter' },
  { name: 'create_user', description: 'Create a new user account (requires WRITE_ENABLED=true)' },
  { name: 'update_user', description: 'Update a user account (requires WRITE_ENABLED=true)' },
  { name: 'list_groups', description: 'List groups with optional search filter' },
  { name: 'create_group', description: 'Create a new assignment group (requires WRITE_ENABLED=true)' },
  { name: 'update_group', description: 'Update a group (requires WRITE_ENABLED=true)' },
  { name: 'add_user_to_group', description: 'Add a user to a group (requires WRITE_ENABLED=true)' },
  { name: 'remove_user_from_group', description: 'Remove a user from a group (requires WRITE_ENABLED=true)' },
  { name: 'create_va_topic', description: 'Create a new Virtual Agent conversation topic. **[Write]**' },
  { name: 'update_va_topic', description: 'Update a Virtual Agent topic properties. **[Write]**' },
  { name: 'get_va_topic', description: 'Get Virtual Agent topic details including intent and trigger phrases' },
  { name: 'list_va_topics_full', description: 'List all Virtual Agent topics with category and status details' },
  { name: 'get_va_conversation', description: 'Get conversation history for a Virtual Agent session' },
  { name: 'list_va_conversations', description: 'List recent Virtual Agent conversations' },
  { name: 'list_va_categories', description: 'List Virtual Agent topic categories' },
  { name: 'list_uib_pages', description: 'List UI Builder pages and their route configurations' },
  { name: 'get_uib_page', description: 'Get details of a specific UI Builder page including layout and child elements' },
  { name: 'create_uib_page', description: 'Create a new UI Builder page with route registration. **[Write]**' },
  { name: 'update_uib_page', description: 'Update an existing UI Builder page. **[Write]**' },
  { name: 'delete_uib_page', description: 'Delete a UI Builder page. **[Write]**' },
  { name: 'list_uib_components', description: 'List available UI Builder components (macroponents) in the instance' },
  { name: 'create_uib_component', description: 'Create a custom UI Builder component (macroponent). **[Scripting]**' },
  { name: 'update_uib_component', description: 'Update a UI Builder component. **[Scripting]**' },
  { name: 'list_uib_data_brokers', description: 'List UI Builder data brokers (data sources for pages)' },
  { name: 'create_uib_data_broker', description: 'Create a UI Builder data broker to feed data to a page. **[Scripting]**' },
  { name: 'list_workspaces', description: 'List all configurable agent workspaces' },
  { name: 'get_workspace', description: 'Get details of a configurable agent workspace including tabs and lists' },
  { name: 'create_workspace', description: 'Create a new configurable agent workspace. **[Write]**' },
  { name: 'configure_workspace_list', description: 'Add or update a list view in an agent workspace. **[Write]**' },
  { name: 'create_ux_app_route', description: 'Register a new route (URL path) in a UX app. **[Write]**' },
  { name: 'create_ux_experience', description: 'Create a new UX Experience (app shell) configuration. **[Write]**' },
];
